# Application Configuration
app:
  name: Qard Hasan for Education API
  version: 1.0.0
  description: Document processing API for Qard Hasan education platform

# Server Configuration
server:
  port: 8080
  servlet:
    context-path: /

# AI Service Configuration
ai:
  gemini:
    api-key: AIzaSyDgKlOMPSrQOY8YbkS9VRxFgJUPVVu7YhM
    base-url: https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-pro:generateContent
    timeout: 30000
    max-retries: 3

# File Upload Configuration
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true
  application:
    name: Qard_hasan_for_education

# Logging Configuration
logging:
  level:
    com.example.Qard_hasan_for_education: DEBUG
    org.springframework.web: INFO
    org.apache.http: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# Document Processing Configuration
document:
  processing:
    supported-types:
      - application/pdf
      - image/jpeg
      - image/png
    max-pages: 50

---
# Development Profile
spring:
  config:
    activate:
      on-profile: dev

logging:
  level:
    root: DEBUG

---
# Production Profile
spring:
  config:
    activate:
      on-profile: prod

logging:
  level:
    root: WARN
    com.example.Qard_hasan_for_education: INFO

ai:
  gemini:
    api-key: ${GEMINI_API_KEY:AIzaSyDgKlOMPSrQOY8YbkS9VRxFgJUPVVu7YhM}